name: easyxml
version: 4
accesskey: 3mlxo4mzjl
cron:
    - description: cron test
          url: reminder?test.php?
          schedule: 00 23 * * *
          timezone: Beijing
    - description: cron test1
          url: reminder?test=4567
          schedule: 05 23 * * *
          timezone: Beijing