name: easyxml
version: 1
accesskey: 3mlxo4mzjl
cron:
    - description: cron test
      url: reminder?receivers=1330441788&msgTxt=%E6%87%92%E8%99%AB%EF%BC%8C%E8%AF%A5%E6%89%93%E6%89%AB%E5%8D%AB%E7%94%9F%E4%BA%86
      schedule: 00 23 * * *